#16_Рекомендованные_статьи
Rinat-G/infosync pull request #31
Opened 2020-12-04 18:26 UTC by Raelav

*Что-то сделано
*Собирается без ошибок
*Некомментированно  и недокументированно
*Нетестировал с базой данных(не могу запустить пока)

2020-12-05 09:13 UTC, Rinat-G requested changes

2020-12-05 09:13 UTC, gimrin commented on infosync-app/src/main/java/ru/urfu/infosync/controller/StuffController.java
> +@RequestMapping(value="/api/stuff", produces = APPLICATION_JSON_VALUE)
почему так странно называется api и, соответственно остальные классы? )

2020-12-05 09:13 UTC, gimrin commented on infosync-app/src/main/java/ru/urfu/infosync/dao/StuffDao.java
> +                groupId
сложно читать, лучше использовать переносы типа такого:

```
 var stuff = jdbcTemplate.query(
                SELECT_RECOMMENDED_POST_BY_GROUP_ID,
                (rs, rowNum) -> new HabrPost(
                        rs.getString("title"), 
                        rs.getString("post_link"),
                        rs.getString("post_body")),
                groupId
        );
```

2020-12-05 09:13 UTC, gimrin commented on infosync-app/src/main/java/ru/urfu/infosync/dao/StuffDao.java
> +        return stuff.size() < 1 ? null : stuff;
Если в сервисе ты возвращаешь список, то зачем здесь null? просто возвращай пустой список, если из базы получил пустой список

2020-12-05 09:13 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/service/StuffService.java
> +        var email = principal.getName();
здесь будет NPE, так как поле не инициализировано

2020-12-05 09:13 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/service/StuffService.java
> +        var email = principal.getName();
ну и вообще, в контексте нет такого бина Principal. ты его можешь получить в аргумент контроллера или другим способом
https://www.baeldung.com/get-user-in-spring-security

2020-12-05 09:13 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/controller/StuffController.java
> +    public List<HabrPost> getStuff() {
Для данной задачи модели HabrPost не достаточно, так как она содержит только заголовок, текст и ссылку. 
Студенту же, на странице постов нужно видеть кем этот пост был порекомендован (преподаватель) и его статус прочтения, чтобы видеть что он отметил, а что нет. 

В рамках этой задачи пока будет достаточно, в следующих задачах мы расширим модель списком написанных эссе и комментариев к ним. Эту часть api еще предстоит обдумать

2020-12-05 09:24 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/controller/StuffController.java
> +@RequestMapping(value="/api/stuff", produces = APPLICATION_JSON_VALUE)
по этому названию совершенно не понятно что прячется за этим api)
мжт назвать как-то по-простому?  типа /api/recommended или /api/student/news
в общем, надо подумать)

2020-12-05 10:12 UTC, Raelav commented on infosync-app/src/main/java/ru/urfu/infosync/controller/StuffController.java
> +    public List<HabrPost> getStuff() {
Да, тут понятно. Это временно подцепил к "HabrPost"

2020-12-05 10:18 UTC, Raelav commented on infosync-app/src/main/java/ru/urfu/infosync/service/StuffService.java
> +        var email = principal.getName();
https://www.codeflow.site/ru/article/spring-security__get-current-logged-in-username-in-spring-security
Там там описывается, что UsernamePasswordAuthenticationToken, использованный тобой ранее вставляет инфу в Principal во время выполнения Spring. Но да, это один из моментов, который я хотел проверить на БД

2020-12-05 10:19 UTC, Raelav commented on infosync-app/src/main/java/ru/urfu/infosync/dao/StuffDao.java
> +        return stuff.size() < 1 ? null : stuff;
Этот кусок я скопипастил откуда то. Доработаю

2020-12-05 10:23 UTC, Raelav commented on infosync-app/src/main/java/ru/urfu/infosync/controller/StuffController.java
> +@RequestMapping(value="/api/stuff", produces = APPLICATION_JSON_VALUE)
Stuff - замена Post, ибо занято. Поэтому я хотел документирование запилить, чтоб при наведении сообщалось что к чему. да, api надо заменить

2020-12-12 16:18 UTC, Rinat-G requested changes
переименуй по конвенциям и можно мерджить

2020-12-12 16:18 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/model/GeneralPost.java
> +    Integer recommended_by_user_id;
предлагаю придерживаться стандартного и общепринятого в java подхода в именовании полей, типов, переменных и методов 
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html
используй camelCase )

2020-12-12 16:18 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/service/UserService.java
> +    public UserDto GetDataOfCurrentUser() {
naming conventions 
+ мне кажется корректней было бы назвать getCurrentUser, ты же возвращаешь объект типа User (хоть и DTO)

2020-12-12 16:18 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/dao/PostDao.java
> +        var news = jdbcTemplate.query(
мелочь )

![image](https://user-images.githubusercontent.com/29258550/101988991-21e4e080-3cbf-11eb-86be-b15c101b9e23.png)

2020-12-20 12:27 UTC, Rinat-G submitted a review, later dismissed

2020-12-20 12:33 UTC, Rinat-G approved these changes

2020-12-20 12:33 UTC, merged