forward post api
Rinat-G/infosync pull request #32
Opened 2020-12-05 12:26 UTC by Rinat-G

resolve #20

2020-12-06 18:50 UTC, Raelav requested changes

2020-12-06 18:50 UTC, Raelav commented on infosync-app/src/main/java/ru/urfu/infosync/dao/GroupDao.java
> +                SELECT_GROUPS_BY_NAMES.replace("$names", inClauseSql),
Мне бы ссылочку где почитать про эти заполнители. У нас есть запрос со списком групп, вместо которых стоят "?". Каким образом в запрос встанут группы из groupNames?

2020-12-06 18:50 UTC, Raelav commented on infosync-app/src/main/java/ru/urfu/infosync/dao/PostDao.java
> +public class PostDao {
У меня вместо PostDao NewsDao. Можно, если у нас обоих все ок сначала смерджить, а потом слить оба Dao, если потребуется

2020-12-06 18:50 UTC, Raelav commented on infosync-app/src/main/java/ru/urfu/infosync/dao/UserDao.java
> +        return ids.size() < 1 ? null : ids.get(0);
Ты мне писал про возвращение null. Это я у тебя скопипастил, однако.

2020-12-06 18:50 UTC, Raelav commented on infosync-app/src/main/java/ru/urfu/infosync/service/ForwardPostService.java
> +public class ForwardPostService {
Я заменил слово Post на News(ранне Stuff) когда начал писать модель  с названием Post. Наверное стоит как в твоей работе использовать более сложные названия

2020-12-12 16:31 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/dao/GroupDao.java
> +                SELECT_GROUPS_BY_NAMES.replace("$names", inClauseSql),
jdbcTemplate принимает массив аргументов которые привязывает к переменным в sql ( вопросительные знаки) 
эм... почитать) почитай про spring jdbc и jdbcTemlate, например тут 
https://www.baeldung.com/spring-jdbc-jdbctemplate

2020-12-12 16:32 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/dao/UserDao.java
> +        return ids.size() < 1 ? null : ids.get(0);
логично, но там был список, а здесь объект. да, nullable логика для объектов это не очень хорошо, но так проще)

2020-12-12 16:33 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/service/ForwardPostService.java
> +public class ForwardPostService {
именование - всегда холиварная тема)

2020-12-12 16:35 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/dao/PostDao.java
> +public class PostDao {
ты уже у себя переименовал, так что не актуально)

2020-12-12 17:22 UTC, Raelav approved these changes

2020-12-12 17:23 UTC, merged