#19 read post
Rinat-G/infosync pull request #33
Opened 2020-12-20 20:40 UTC by Raelav

2020-12-22 20:34 UTC, Rinat-G requested changes

2020-12-22 20:34 UTC, gimrin commented on infosync-app/src/main/java/ru/urfu/infosync/controller/PostStatusController.java
> +@RequestMapping(value = "/api/news/{postId:\\d+}")
C точки зрения RESTful API не корректный выбор пути и метода GET. 
Метод GET всегда подразумевается как идемпотентный, то есть не должен изменять состояние системы. Обращаясь к API `/api/news/{postId:\\d+}` методом GET я бы предполагал что я получу конкретный пост, а не поменяю его состояние.  

Возможно не самое элегантное решение с точки зрения проектирования REST API, но я бы предложил следующее.
У нас уже есть контроллер, обрабатывающий запросы к `/api/news` - PostController. Возможно стоит добавить к нему метод, проставляющий статусы. Он должен быть именно POST метод, так как это правильнее с точки зрения REST API.
```
@PostMapping("/{postId:\\d+}/readed")
public void setPostStatus(@PathVariable Integer postId) {
    postStatusService.markAsRead(postId);
}
```
Таким образом разные методы контроллера будут обрабатывать разные дочерние пути для  `/api/news`.


Рекомендую почитать эту цепочку статей для старта:
https://habr.com/ru/post/483202/
ну и далее любую литературу или статьи по разработке RESTful API.

2020-12-22 20:34 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/model/PostStatus.java
> +    Integer post_id;
Переименуй по Java Naming Conventions плз.

2020-12-22 20:34 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/service/PostStatusService.java
> +public class PostStatusService {
Service обычно является инструментом бизнес-логики. В нашем случае проставление статуса посту сильно связано логикой с самим объектом "Post". Пока не предлагаю объединять модель GeneralPost и статус поста (возможно это и не понадобится), но с точки зрения нашей простой логики было бы логично это видеть метод markAsRead в классе PostService.

2020-12-22 20:34 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/dao/UserDao.java
> +    //Где-то читал, что SELECT * используют только если нужны все столбцы из строки
Все верно)

2020-12-22 20:34 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/dao/UserDao.java
>          var ids = jdbcTemplate.query(
возможно jdbcTemplate.query() лучше заменить на jdbcTemplate.queryForObject()
;)

2020-12-22 20:34 UTC, Rinat-G commented on infosync-app/src/main/java/ru/urfu/infosync/service/UserService.java
>       */
кстати коммент не соответствует тому что возвращается из метода)

2020-12-23 03:22 UTC, Raelav commented on infosync-app/src/main/java/ru/urfu/infosync/service/UserService.java
>       */
это да. Метод переделал(между коммитами), а про коммент забыл

2021-01-11 18:05 UTC, Rinat-G approved these changes

2021-01-11 18:05 UTC, merged