create DDL model
Rinat-G/infosync pull request #4
Opened 2020-11-24 09:25 UTC by Rinat-G

fix #2

2020-11-24 09:29 UTC, Raelav commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +CREATE SCHEMA "INFOSYNC";
Comment

2020-11-24 09:34 UTC, Raelav commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +--changeset gimaletdinov-rr:infosync_ddl_initial_001 runOnChange:true failOnError:true
testCommen2

2020-11-24 09:34 UTC, Raelav commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM pg_tables WHERE  schemaname = 'INFOSYNC' AND tablename  = 'GROUP'
TestComment3

2020-11-24 09:36 UTC, Rinat-G commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +--changeset gimaletdinov-rr:infosync_ddl_initial_001 runOnChange:true failOnError:true
dsfsdf

2020-11-24 09:36 UTC, Rinat-G commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM pg_tables WHERE  schemaname = 'INFOSYNC' AND tablename  = 'GROUP'
asdasd

2020-11-24 09:38 UTC, Raelav requested changes
text

2020-11-24 11:04 UTC, Raelav requested changes

2020-11-24 11:04 UTC, Raelav commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +    "ID"   BIGINT GENERATED BY DEFAULT AS IDENTITY,
"ID" выглядит слишком абстрактно. "ID_GROUP" или "GROUP_ID" - более информативно. Возможно я ошибаюсь, но намного лучше будет выглядеть, когда одинаковые столбцы будут нести одно имя. В Postgre это также позволяет референцах указывать всего лишь названием таблицы без указания имени.

2020-11-24 11:04 UTC, Raelav commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +    CONSTRAINT "GROUP_PK" PRIMARY KEY ("ID"),
Возможно более удобно отказаться от CONSTRAINT к PRIMARY KEY. Так как это ограничение должно быть в каждой таблице. В общем выглядит избыточно и не сразу видно PRIMARY KEY, хотя я могу ошибаться и на это есть некий стандарт.

2020-11-25 09:05 UTC, Rinat-G commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +    "ID"   BIGINT GENERATED BY DEFAULT AS IDENTITY,
ID в контексте таблицы группа выглядит как GROUP.ID 
ты не можешь в запросе обращаться к полю таблицы без указания группы. 
А если сделать имя поля как GROUP_ID, то обращение будет как GROUP.GROUP_ID, что выглядит слишком многословно и странно

2020-11-25 09:11 UTC, Rinat-G commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +    CONSTRAINT "GROUP_PK" PRIMARY KEY ("ID"),
Наличие CONSTRAINT задает идентификатор (GROUP_PK)твоему ограничению, которым является PRIMARY KEY. По этому идентификатору можно обращаться к констрейту, менять его или удалять и т.д. Да, это некоторый стандарт, наверное, так как при генерации таблиц прописывается именно так.  Можно и без него, наверное, но предлагаю оставить так.

2020-11-25 09:15 UTC, Raelav commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +    "ID"   BIGINT GENERATED BY DEFAULT AS IDENTITY,
На мой взгляд ни разу не странно. Если тут тебе кажется это странным, то допустим в таблице ESSAY там несколько id и при обращении будет: ESSAY.ESSAY_ID, ESSAY.POST_ID, ESSAY.USER_ID (ну или во втором варианте ID в NAME_ID поставить наоборот ID_NAME. как вариант)

2020-11-25 09:50 UTC, Rinat-G commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +    "ID"   BIGINT GENERATED BY DEFAULT AS IDENTITY,
все, я понял о чем ты. ты о внешних ключах, которые ссылаются на поле ID другой таблицы. 
ты прав, если речь о таблице ESSAY, например, то внешние ключи ссылающиеся на ID лучше помечать как  POST_ID.
Сейчас поправлю.

2020-11-25 10:27 UTC, Raelav requested changes

2020-11-25 10:27 UTC, Raelav commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +    "SALT"       VARCHAR      NOT NULL,
SALT? What's that? Что-то по названию не совсем понятно что это.

2020-11-25 10:27 UTC, Raelav commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +    "RECOMMENDED_BY_ID" BIGINT  NOT NULL,
RECOMMENDED_BY_USER_ID. Возможно так понятнее. (recommended by rating,  recommended by comment). Возможно ты посчитаешь это слишком длинным, но это из-за длины первого слова так кажется.

2020-11-25 10:27 UTC, Raelav commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +    "MARK_BY_ID" BIGINT NOT NULL,
Тут то же. Хотя в данном месте более очевидно, что имеется ввиду USER, но если согласен с предыдущим, то ради однообразия следует и тут заменить на MARK_BY_USER_ID

2020-11-25 10:47 UTC, Rinat-G commented on db-scripts/liquibase/sql/0001_InfoSync_ddl_initial.sql
> +    "SALT"       VARCHAR      NOT NULL,
динамическая соль для формирования хэша пароля
https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D0%BB%D1%8C_(%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F)

2020-11-25 11:10 UTC, Raelav approved these changes

2020-11-25 11:15 UTC, merged